Disable portainer auto-deploy again Fixes #1189

diff --git a/.github/workflows/dev_release.yaml b/.github/workflows/dev_release.yaml
--- a/.github/workflows/dev_release.yaml
+++ b/.github/workflows/dev_release.yaml
@@ -64,30 +64,30 @@ jobs:
           build-args: |
             VERSION="dev (${{ env.sha_short}})"
 
-  deploy:
-    runs-on: ubuntu-latest
-    needs: build-and-push-image
-    environment: development
-    steps:
-      # -L makes curl follow the redirect from cloudflare
-      # -w captures the HTTP code
-      # -s is silent so no progress bar shows
-      # -o /dev/null sends the response to null so it doesn't contaminate the response code
-      # -H adds the two Cloudflare headers to allow webhook access
-      - name: Deploy to Portainer
-        run: |
-          status_code=$(curl -v -X POST \
-            -L \
-            -w "%{http_code}" \
-            -s \
-            -o /dev/null \
-            -H "CF-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID }}" \
-            -H "CF-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}" \
-            "${{ vars.PORTAINER_WEBHOOK_URL }}")
-          echo "Status code received: $status_code"
-          if [ $status_code -eq 204 ]; then
-            echo "Deployment succeeded"
-          else
-            echo "Deployment failed"
-            exit 1
-          fi
+  # deploy:
+  #   runs-on: ubuntu-latest
+  #   needs: build-and-push-image
+  #   environment: development
+  #   steps:
+  #     # -L makes curl follow the redirect from cloudflare
+  #     # -w captures the HTTP code
+  #     # -s is silent so no progress bar shows
+  #     # -o /dev/null sends the response to null so it doesn't contaminate the response code
+  #     # -H adds the two Cloudflare headers to allow webhook access
+  #     - name: Deploy to Portainer
+  #       run: |
+  #         status_code=$(curl -v -X POST \
+  #           -L \
+  #           -w "%{http_code}" \
+  #           -s \
+  #           -o /dev/null \
+  #           -H "CF-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID }}" \
+  #           -H "CF-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}" \
+  #           "${{ vars.PORTAINER_WEBHOOK_URL }}")
+  #         echo "Status code received: $status_code"
+  #         if [ $status_code -eq 204 ]; then
+  #           echo "Deployment succeeded"
+  #         else
+  #           echo "Deployment failed"
+  #           exit 1
+  #         fi
