Turn off portainer deployment for now Fixes #889

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -62,30 +62,31 @@ jobs:
           cache-from: type=registry,ref=neilenns/vatsim-plan-verifier-${{ matrix.context }}:latest
           cache-to: type=inline
 
-  deploy:
-    runs-on: ubuntu-latest
-    needs: build-and-push-image
-    environment: production
-    steps:
-      - name: Deploy to Portainer
-        # -L makes curl follow the redirect from cloudflare
-        # -w captures the HTTP code
-        # -s is silent so no progress bar shows
-        # -o /dev/null sends the response to null so it doesn't contaminate the response code
-        # -H adds the two Cloudflare headers to allow webhook access
-        run: |
-          status_code=$(curl -X POST \
-            -L \
-            -w "%{http_code}" \
-            -s \
-            -o /dev/null \
-            -H "CF-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID }}" \
-            -H "CF-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}" \
-            "${{ secrets.PORTAINER_WEBHOOK_URL }}")
-          echo "Status code received: $status_code"
-          if [ $status_code -eq 200 ]; then
-             echo "Deployment succeeded"
-          else
-             echo "Deployment failed"
-             exit 1
-          fi
+  # Issue 889: Disable for now until Portainer fixes the bug on their end preventing this from working
+  # deploy:
+  #   runs-on: ubuntu-latest
+  #   needs: build-and-push-image
+  #   environment: production
+  #   steps:
+  #     - name: Deploy to Portainer
+  # -L makes curl follow the redirect from cloudflare
+  # -w captures the HTTP code
+  # -s is silent so no progress bar shows
+  # -o /dev/null sends the response to null so it doesn't contaminate the response code
+  # -H adds the two Cloudflare headers to allow webhook access
+  # run: |
+  #   status_code=$(curl -X POST \
+  #     -L \
+  #     -w "%{http_code}" \
+  #     -s \
+  #     -o /dev/null \
+  #     -H "CF-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID }}" \
+  #     -H "CF-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}" \
+  #     "${{ secrets.PORTAINER_WEBHOOK_URL }}")
+  #   echo "Status code received: $status_code"
+  #   if [ $status_code -eq 200 ]; then
+  #      echo "Deployment succeeded"
+  #   else
+  #      echo "Deployment failed"
+  #      exit 1
+  #   fi
